<?php

/*
====================================================
 SEARCH - BACKEND
 File: search.php
====================================================

This file is currently running in DEMO MODE.
A Search API can be added here later.

Frontend:
results.html
      ↓
search.php
      ↓
Search API
      ↓
JSON Response
============================================== */

/*  JSON RESPONSE HEADER */

header("Content-Type: application/json; charset=UTF-8");


/*  ALLOW GET REQUEST ONLY */

if ($_SERVER["REQUEST_METHOD"] !== "GET") {
    http_response_code(405);
    echo json_encode([
        "success" => false,
        "error" => "Only GET requests are allowed."
    ]);
    exit;
}

/* GET SEARCH QUERY */

$query = isset($_GET["q"])
    ? trim($_GET["q"])
    : "";

/* CHECK QUERY */

if ($query === "") {
    http_response_code(400);
    echo json_encode([
        "success" => false,
        "error" => "Search query is missing."
    ]);
    exit;
}


/* LIMIT QUERY LENGTH  */

if (mb_strlen($query) > 200) {
    http_response_code(400);
    echo json_encode([
        "success" => false,
        "error" => "Search query is too long."
    ]);
    exit;
}

/* ================================================
   DEMO RESULTS
------------------------------------------
No Search API has been integrated here.

Therefore, demo results are being generated for testing purposes.

This section can later be replaced with an API request.
================================================ */

/* To safely encode JSON,
   raw user input is no longer being sent
   directly as HTML. */


$demoResults = [

    [
        "title" =>
            "Search result for: " . $query,
        "url" =>
            "https://example.com",
        "description" =>
            "This is a demo search result generated by Pipilika Search backend."
    ],

    [
        "title" =>
            "Learn more about " . $query,
        "url" =>
            "https://example.com",
        "description" =>
            "Your real search API will be connected to this backend later."
    ],

    [
        "title" =>
            "Pipilika Search Demo",
        "url" =>
            "https://pipilikasearch.kesug.com/",
        "description" =>
            "Pipilika Search is currently running in learning and testing mode."
    ]
];

/* ================================================
   FINAL JSON RESPONSE
================================================ */
$response = [
    "success" => true,
    "query" => $query,
    "total" => count($demoResults),
    "results" => $demoResults
];

/* ================================================
   SEND RESPONSE
================================================ */

echo json_encode(
    $response,
    JSON_UNESCAPED_SLASHES |
    JSON_UNESCAPED_UNICODE
);
exit;
?>
